---
# Test playbook for Drone Runner Exec configuration

- name: Define drone-runner-exec group dynamically
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host to drone_runner_exec_hosts group if it has the role
      ansible.builtin.group_by:
        key: "drone_runner_exec_hosts"
      when: "'drone-runner-exec' in hostvars[inventory_hostname].get('host_roles', [])"

- name: Import Drone Runner Exec configuration playbook
  hosts: drone_runner_exec_hosts
  become: true
  gather_facts: true
  roles:
    - drone-runner-exec

- name: Validate Drone Runner Exec configuration
  hosts: drone_runner_exec_hosts
  become: true
  gather_facts: true
  tasks:
    - name: Include drone-runner-exec default variables for validation
      ansible.builtin.include_vars:
        file: "defaults/main.yml"

    - name: Include host-specific variables for validation
      ansible.builtin.include_vars:
        file: "vars/main.yml"
      failed_when: false

    - name: Import Drone Runner Exec test tasks
      ansible.builtin.import_tasks: "tasks/test.yml"
