---
- name: Setup dnsdist
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    dnsdist_conf_path: /etc/dnsdist/dnsdist.conf
    custom_lua_path: /etc/dnsdist
    dnsdist_console_key: "{{ lookup('env', 'DNSDIST_CONSOLE_KEY') }}"

  tasks:
    - name: Update Timezone to America/Chicago
      copy: 
        content: |
          "America/Chicago\n" 
        dest: /etc/timezone 
        owner: root 
        group: root 
        mode: 0644
      register: timezone

    - name: Reconfigure Timezone Data (if changed)
      shell: dpkg-reconfigure -f noninteractive tzdata
      when: timezone.changed

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install APT packages
      apt:
        pkg:
          - dnsdist
          - net-tools
          - rsyslog
        state: latest

    - name: Make sure dnsdist.conf destination dir exists
      file:
        path: "{{ dnsdist_conf_path | dirname }}"
        state: directory

    - name: Create dnsdist.conf
      template:
        src: dnsdist.conf.j2
        dest: "{{ dnsdist_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      register: dnsdist_conf

    - name: Make sure custom lua path dir exists
      file:
        path: "{{ custom_lua_path }}"
        state: directory

    - name: Create orderedwrandom Lua policy
      copy:
        src: orderedwrandom.lua
        dest: "{{ custom_lua_path }}/orderedwrandom.lua"
        owner: root
        group: root
        mode: '0644'
      register: orderedwrandom_lua

    - name: restart dnsdist
      service:
        name: dnsdist
        state: restarted
      when: dnsdist_conf.changed or orderedwrandom_lua.changed

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Create rsyslog configuration file for dnsdist
      copy:
        dest: /etc/rsyslog.d/dnsdist.conf
        content: |
          :syslogtag, startswith, "dnsdist" action(type="omfwd" target="{{ remote_syslog_server }}" port="{{ remote_syslog_server_port }}" protocol="udp")
        owner: root
        group: root
        mode: 0644
      notify: Restart rsyslog

  handlers:
    - name: Restart rsyslog
      systemd:
        name: rsyslog
        state: restarted
