---
# NVIDIA GPU UV Package Manager Installation Tasks

- name: Check if uv is already installed
  ansible.builtin.command:
    cmd: uv --version
  register: uv_version_check
  changed_when: false
  failed_when: false
  when: install_uv | bool

- name: Install uv package manager
  block:
    - name: Create temp directory for uv installation
      ansible.builtin.tempfile:
        state: directory
        suffix: uv
      register: uv_temp_dir

    - name: Download uv installer script
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        dest: "{{ uv_temp_dir.path }}/install.sh"
        mode: "0755"
      register: uv_script_download

    - name: Run uv installer script
      ansible.builtin.command:
        cmd: ./install.sh
        chdir: "{{ uv_temp_dir.path }}"
      register: uv_install
      changed_when: uv_install.rc == 0

    - name: Clean up temp directory
      ansible.builtin.file:
        path: "{{ uv_temp_dir.path }}"
        state: absent
  when:
    - install_uv | bool
    - uv_version_check.rc != 0
