---
- name: Install pihole
  hosts: all
  become: yes
  vars:
    setupVars_path: /etc/pihole/setupVars.conf
    web_password: "{{ lookup('env', 'PIHOLE_WEB_PASSWORD_HASH') }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install APT packages
      apt:
        pkg:
          - curl
          - python3-pip
          - python3-boto3
          - python3-packaging
        state: latest
    
    - name: Make sure destination dir exists
      file:
        path: "{{ setupVars_path | dirname }}"
        state: directory

    - name: Create setupVars.conf
      template:
        src: setupVars.conf.j2
        dest: "{{ setupVars_path }}"
        owner: root
        group: root
        mode: '0644'
    
    # Install/update pihole
    - name: Run pihole install
      shell: set -o pipefail && curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
      args:
        executable: /usr/bin/bash
      register: ps

    - debug: var=ps.stdout_lines
    - debug: var=ps.stderr_lines

    ## Chicken & egg: on initial setup, pihole needs teleporter backup restored to provide these values ...
    ## but to get teleporter backup, needs to lookup local s3 host :/ Hard-coding for now.
    ## 
    # dig @localhost synology.cusack-ruth.name AAAA synology.cusack-ruth.name A | \
    # grep -A 1 'ANSWER SECTION' | grep IN | awk '{print $NF}' | \
    # xargs -I {} echo {} synology.cusack-ruth.name
    ## 
    - name: Get synology DNS records from pihole
      shell: |
        echo "192.168.7.165 synology.cusack-ruth.name"
      register: synology_hosts_entries
    
    - name: Copy synology hosts entries to /etc/hosts
      blockinfile:
        path: /etc/hosts
        marker: "{mark} synology"
        block: "{{ synology_hosts_entries.stdout }}"

    - name: Copy teleporter backup to remote
      amazon.aws.s3_object:
        access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        endpoint_url: http://synology.cusack-ruth.name:9000
        bucket: homelab-configurations
        object: pihole/pi-hole-pihole-teleporter.tar.gz
        dest: /root/pi-hole-pihole-teleporter.tar.gz
        mode: get
    
    - name: Download pihole_restore
      shell: |
        curl -L -O https://github.com/chamilad/pihole-restore/releases/download/v0.1.0/pihole_restore-v0.1.0-linux-x86_64
        mv pihole_restore-v0.1.0-linux-x86_64 pihole_restore
        chmod +x pihole_restore

    - name: Restore pihole
      command: /root/pihole_restore -f /root/pi-hole-pihole-teleporter.tar.gz -c
      register: ps
