---
# NVIDIA GPU Configuration Playbook

- name: Configure NVIDIA GPU system for AI/ML/CUDA
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Import base package management tasks
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: Import GPU setup tasks
      ansible.builtin.import_tasks: tasks/gpu_setup.yml
      when: nvidia_install_gpu_drivers | bool or nvidia_install_cuda_toolkit | bool or nvidia_configure_egpu | bool

    - name: Import btop installation tasks
      ansible.builtin.import_tasks: tasks/btop.yml
      when: nvidia_install_btop | bool

    - name: Import Ollama installation tasks
      ansible.builtin.import_tasks: tasks/ollama.yml
      when: nvidia_install_ollama | bool

    - name: Import UV package manager installation tasks
      ansible.builtin.import_tasks: tasks/uv_manager.yml
      when: nvidia_install_uv | bool

  handlers:
    - name: Update initramfs
      ansible.builtin.command:
        cmd: update-initramfs -u
      changed_when: true
