---
# NVIDIA GPU Configuration Playbook

- name: Configure NVIDIA GPU system for AI/ML/CUDA
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Import base package management tasks
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: Import GPU setup tasks
      ansible.builtin.import_tasks: tasks/gpu_setup.yml
      when: nvidia_install_gpu_drivers | bool or nvidia_install_cuda_toolkit | bool or nvidia_configure_egpu | bool

    - name: Import btop installation tasks
      ansible.builtin.import_tasks: tasks/btop.yml
      when: install_btop | bool

    - name: Import Ollama installation tasks
      ansible.builtin.import_tasks: tasks/ollama.yml
      when: install_ollama | bool

    - name: Import UV package manager installation tasks
      ansible.builtin.import_tasks: tasks/uv_manager.yml
      when: install_uv | bool
      
    - name: Import n8n AI workflow platform tasks
      ansible.builtin.import_tasks: tasks/n8n.yml
      when: install_n8n | bool
      
    - name: Import Whisper ASR Webservice tasks
      ansible.builtin.import_tasks: tasks/whisper_asr.yml
      when: install_whisper_asr | bool
      
    - name: Import Open WebUI tasks
      ansible.builtin.import_tasks: tasks/open_webui.yml
      when: install_open_webui | bool
      
    - name: Import ComfyUI tasks
      ansible.builtin.import_tasks: tasks/comfyui.yml
      when: install_comfyui | bool
      
    - name: Import shared models tasks
      ansible.builtin.import_tasks: tasks/shared_models.yml
      when: install_shared_models | bool
      
    - name: Import GPT Researcher tasks
      ansible.builtin.import_tasks: tasks/gpt_researcher.yml
      when: install_gpt_researcher | bool

  handlers:
    - name: Update initramfs
      ansible.builtin.command:
        cmd: update-initramfs -u
      changed_when: true
      
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
