---
kind: pipeline
type: docker
name: build

steps:
  - name: pkgx
    # image: pkgxdev/pkgx
    image: pkgxdev/pkgx@sha256:610bbc17475cb174c5e6a8a9e3cdf39decb93c552fa073542b6f593255e1cb0c
    commands:
      - apt-get update && apt-get install -y dnsutils netcat
      - mkdir -p ~/.ssh
      - echo "$drone_ssh_priv_key" > ~/.ssh/id
      - chmod -R 700 ~/.ssh
      - chmod 600 ~/.ssh/id
      - ./pkgx-deploy.sh
    environment:
      PM_API_TOKEN_SECRET:
        from_secret: PM_API_TOKEN_SECRET
      PM_API_TOKEN_ID:
        from_secret: PM_API_TOKEN_ID
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      PIHOLE_WEB_PASSWORD_HASH:
        from_secret: PIHOLE_WEB_PASSWORD_HASH
      DNSDIST_CONSOLE_KEY:
        from_secret: DNSDIST_CONSOLE_KEY
      ansible_pihole_vars_main_yml:
        from_secret: ansible_pihole_vars_main_yml
      common_tfbackend:
        from_secret: common_tfbackend
      dnsdist_tfstate_key:
        from_secret: dnsdist_tfstate_key
      blue_pihole_tfstate_key:
        from_secret: blue_pihole_tfstate_key
      green_pihole_tfstate_key:
        from_secret: green_pihole_tfstate_key
      dnsdist_tfvars:
        from_secret: dnsdist_tfvars
      pihole_blue_tfvars:
        from_secret: pihole_blue_tfvars
      pihole_green_tfvars:
        from_secret: pihole_green_tfvars
      pihole_default_tfvars:
        from_secret: pihole_default_tfvars
      drone_ssh_priv_key:
        from_secret: drone_ssh_priv_key

---
kind: pipeline
type: docker
name: notify-on-fail

steps:
- name: pushover
  # this is a fork of plugins/pushover, which currently throws an error
  # https://github.com/drone-plugins/drone-pushover/issues/17
  # https://github.com/drone/drone-template-lib/pull/13
  # image: tmacro/drone-pushover
  image: tmacro/drone-pushover@sha256:0a60ff10cd77fee59444571c827c278faa8c18afc1950e40558c5692d6518125
  settings:
    token: 
      from_secret: PUSHOVER_TOKEN
    user: 
      from_secret: PUSHOVER_USER_ID
    message: "{{ repo.name }} - Pipeline Failure"

trigger:
  status:
    - failure

depends_on:
- build
