---
kind: pipeline
type: docker
name: build

steps:
  - name: check-changes
    image: alpine/git
    commands:
      - |
        echo "Checking for relevant file changes..."
        if git diff --name-only HEAD~1 | grep -E "^(ansible/dnsdist/|ansible/pihole/|dns/|modules/|deploy\.sh|pkgx-deploy\.sh|setup-ansible\.sh|\.drone\.yml)"; then
          echo "✅ DNS/infrastructure files changed, proceeding with deployment"
          exit 0
        else
          echo "ℹ️ No DNS/infrastructure files changed, skipping deployment"
          exit 78
        fi
  - name: unlock-secrets
    image: betalabs/drone-git-crypt
    pull: always
    environment:
      GIT_CRYPT_KEY:
        from_secret: git-crypt-key
  - name: pkgx
    # image: pkgxdev/pkgx
    image: pkgxdev/pkgx@sha256:610bbc17475cb174c5e6a8a9e3cdf39decb93c552fa073542b6f593255e1cb0c
    commands:
      - apt-get update && apt-get install -y dnsutils netcat-traditional
      - mkdir -p ~/.ssh
      - echo "$drone_ssh_priv_key" > ~/.ssh/id_rsa
      - chmod -R 700 ~/.ssh
      - chmod 600 ~/.ssh/id_rsa
      - ./pkgx-deploy.sh
    environment:
      PM_API_TOKEN_SECRET:
        from_secret: PM_API_TOKEN_SECRET
      PM_API_TOKEN_ID:
        from_secret: PM_API_TOKEN_ID
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      PIHOLE_WEB_PASSWORD_HASH:
        from_secret: PIHOLE_WEB_PASSWORD_HASH
      DNSDIST_CONSOLE_KEY:
        from_secret: DNSDIST_CONSOLE_KEY

---
kind: pipeline
type: docker
name: notify-on-fail

steps:
  - name: pushover
    # this is a fork of plugins/pushover, which currently throws an error
    # https://github.com/drone-plugins/drone-pushover/issues/17
    # https://github.com/drone/drone-template-lib/pull/13
    # image: tmacro/drone-pushover
    image: tmacro/drone-pushover@sha256:0a60ff10cd77fee59444571c827c278faa8c18afc1950e40558c5692d6518125
    settings:
      token:
        from_secret: PUSHOVER_TOKEN
      user:
        from_secret: PUSHOVER_USER_ID
      message: "{{ repo.name }} - Pipeline Failure"

trigger:
  status:
    - failure

depends_on:
  - build
