# Enable only necessary linters for this repo
ENABLE_LINTERS:
  - TERRAFORM_TERRAFORM_FMT
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - BASH_SHELLCHECK
  - ANSIBLE_ANSIBLE_LINT

DISABLE_LINTERS:
  - REPOSITORY_GIT_DIFF
APPLY_FIXES: none
VALIDATE_ALL_CODEBASE: true
UPDATED_SOURCES_REPORTER: false
