---
collections:
  - name: amazon.aws
    version: ">=10.1.0"
  - name: ansible.utils
    version: ">=6.0.0"
  - name: community.general
    version: ">=10.7.0"
  - name: kubernetes.core
    version: ">=6.2.0"
  - name: artis3n.tailscale
    version: ">=1.2.0"
