---
# Test playbook for Watchtower configuration

- name: Define watchtower group dynamically
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host to watchtower_hosts group if it has the role
      ansible.builtin.group_by:
        key: "watchtower_hosts"
      when: "'watchtower' in hostvars[inventory_hostname].get('host_roles', [])"

- name: Import Watchtower configuration playbook
  hosts: watchtower_hosts
  become: true
  gather_facts: true
  roles:
    - watchtower

- name: Validate Watchtower configuration
  hosts: watchtower_hosts
  become: true
  gather_facts: true
  tasks:
    - name: Include watchtower default variables for validation
      ansible.builtin.include_vars:
        file: "defaults/main.yml"

    - name: Include host-specific variables for validation
      ansible.builtin.include_vars:
        file: "vars/main.yml"
      failed_when: false

    - name: Import Watchtower test tasks
      ansible.builtin.import_tasks: "tasks/test.yml"
