---
# Test playbook for Watchtower configuration

- name: Import Watchtower configuration playbook
  hosts: all
  become: true
  roles:
    - watchtower

- name: Validate Watchtower configuration
  hosts: all
  become: true
  tasks:
    - name: Import Watchtower test tasks
      ansible.builtin.import_tasks: tasks/test.yml
