---
galaxy_info:
  author: Claude
  description: Ansible role to configure an Ubuntu system with NVIDIA GPU for AI/ML/CUDA workloads
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - nvidia
    - gpu
    - cuda
    - ai
    - ml
    - machine-learning
    - linux
  dependencies: []