---
name: DNS Infrastructure Deployment

"on":
  push:
    branches: ["main"]
    paths:
      - "services/dnsdist/**"
      - "services/pihole/**"
      - "infrastructure/dns/**"
      - "infrastructure/modules/**"
      - "deploy.sh"
      - "pkgx-deploy.sh"
      - "setup-services.sh"
      - ".gitea/workflows/infrastructure-deploy.yml"

jobs:
  dns-infrastructure-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unlock git-crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: setup-pkgx
        uses: pkgxdev/setup@v4
        with:
          +: ssh

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y dnsutils netcat-traditional

      - name: Deploy DNS infrastructure
        run: |
          mkdir -p ~/.ssh
          echo -n '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ./pkgx-deploy.sh
        env:
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PIHOLE_WEB_PASSWORD_HASH: ${{ secrets.PIHOLE_WEB_PASSWORD_HASH }}
          DNSDIST_CONSOLE_KEY: ${{ secrets.DNSDIST_CONSOLE_KEY }}

      - name: pushover-actions
        uses: umahmood/pushover-actions@main
        if: failure()
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: "DNS Infrastructure Deployment"
          message: "${{ job.status }} - ${{ github.actor }} - ${{ github.event.head_commit.message }}"
