---
name: Services Deployment Workflow

"on":
  push:
    branches: [main]
    paths:
      - "services/**"
      - "setup-ansible.sh"
      - "services-deploy.sh"
      - "services-pkgx-deploy.sh"
      - ".gitea/workflows/services-deploy.yml"

jobs:
  services-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unlock git-crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: setup-pkgx
        uses: pkgxdev/setup@v4
        with:
          +: ansible
            ssh
            python

      - name: Install dependencies
        run: |
          echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
          apt-get update
          apt-get install -y dnsutils netcat-traditional git-crypt

      - name: check-changes
        id: check_changes
        run: |
          echo "Checking for relevant file changes..."
          if git diff --name-only HEAD~1 | grep -E "^(services/|setup-services\.sh|services-deploy\.sh|services-pkgx-deploy\.sh|services-deploy\.yml)"; then
            echo "✅ Services files changed, proceeding with deployment"
            # Create a file to track which playbooks should be deployed
            rm -f .deploy_playbooks 2>/dev/null || true
            touch .deploy_playbooks

            echo "Detecting which roles were changed..."

            # Check for changes in common files that should trigger full deployment
            if git diff --name-only HEAD~1 | \
               grep -E "^(services/inventory\.yml|services/infrastructure\.yml|services/ansible\.cfg|setup-services\.sh|services-deploy\.sh)"; then
              echo "✅ Common services files changed, will run full deployment"
              echo "FULL_DEPLOYMENT" > .deploy_playbooks
              echo "::set-output name=deploy_full::yes"
              exit 0
            fi
            # Check for each role directory and add to deploy list if changed
            git diff --name-only HEAD~1 \
              | grep -E "^services/(disk-monitoring|drone|gitea|nut|nvidia-gpu|watchtower)" \
              | sed -E 's#^services/(disk-monitoring|drone-runner-exec|drone|gitea-act-runner|gitea|nut|nvidia-gpu|watchtower).*#services/\1-only.yml#' \
              | sort -u > .deploy_playbooks

            # Count how many playbooks will be deployed
            PLAYBOOK_COUNT=$(wc -l < .deploy_playbooks)
            if [ "$PLAYBOOK_COUNT" -gt 0 ]; then
              echo "✅ Will deploy ${PLAYBOOK_COUNT} role(s)"
              echo "::set-output name=deploy_partial::yes"
            else
              echo "ℹ️ No specific roles changed"
            fi
            exit 0
          else
            echo "ℹ️ No relevant Ansible files changed, skipping deployment"
          fi

      - name: deploy-roles
        if: steps.check_changes.outputs.deploy_full == 'yes'
        run: |
          echo -n '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa.tmp
          chmod 600 id_rsa.tmp

          ./services-pkgx-deploy.sh --playbook=services/infrastructure.yml "--private-key id_rsa.tmp"

      - name: deploy-changed-roles
        if: steps.check_changes.outputs.deploy_partial == 'yes'
        run: |
          echo -n '${{ secrets.SSH_PRIVATE_KEY }}' > id_rsa.tmp
          chmod 600 id_rsa.tmp

          while IFS= read -r playbook; do
            echo "Deploying $playbook"
            ./services-pkgx-deploy.sh --playbook="$playbook" "--private-key id_rsa.tmp"
          done < .deploy_playbooks

      - name: pushover-actions
        uses: umahmood/pushover-actions@main
        if: failure()
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: "${{ github.workflow }}"
          message: "${{ job.status }} - ${{ github.actor }} - ${{ github.event.head_commit.message }}"
