---
- name: Setup dnsdist
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  vars:
    dnsdist_conf_path: /etc/dnsdist/dnsdist.conf
    custom_lua_path: /etc/dnsdist
    dnsdist_console_key: "{{ lookup('env', 'DNSDIST_CONSOLE_KEY') }}"

  tasks:
    - name: Reconfigure Timezone Data
      ansible.builtin.shell: timedatectl set-timezone America/Chicago && dpkg-reconfigure -f noninteractive tzdata
      changed_when: false

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install APT packages
      ansible.builtin.apt:
        pkg:
          - dnsdist
          - net-tools
          - rsyslog
        state: present

    - name: Make sure dnsdist.conf destination dir exists
      ansible.builtin.file:
        path: "{{ dnsdist_conf_path | dirname }}"
        state: directory
        mode: "0755"

    - name: Create dnsdist.conf
      ansible.builtin.template:
        src: dnsdist.conf.j2
        dest: "{{ dnsdist_conf_path }}"
        owner: root
        group: root
        mode: "0644"
      register: dnsdist_conf

    - name: Make sure custom lua path dir exists
      ansible.builtin.file:
        path: "{{ custom_lua_path }}"
        state: directory
        mode: "0755"

    - name: Create orderedwrandom Lua policy
      ansible.builtin.copy:
        src: orderedwrandom.lua
        dest: "{{ custom_lua_path }}/orderedwrandom.lua"
        owner: root
        group: root
        mode: "0644"
      register: orderedwrandom_lua

    - name: Restart dnsdist
      ansible.builtin.service:
        name: dnsdist
        state: restarted
      when: dnsdist_conf.changed or orderedwrandom_lua.changed

    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: Create rsyslog configuration file for dnsdist
      ansible.builtin.copy:
        dest: /etc/rsyslog.d/dnsdist.conf
        content: |
          :syslogtag, startswith, "dnsdist" action(type="omfwd" target="{{ remote_syslog_server }}" port="{{ remote_syslog_server_port }}" protocol="udp")
        owner: root
        group: root
        mode: "0644"
      notify: Restart rsyslog

  handlers:
    - name: Restart rsyslog
      ansible.builtin.systemd:
        name: rsyslog
        state: restarted
