---
# Test playbook for Drone CI configuration

- name: Define drone group dynamically
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host to drone_hosts group if it has the role
      ansible.builtin.group_by:
        key: "drone_hosts"
      when: "'drone' in hostvars[inventory_hostname].get('host_roles', [])"
      changed_when: false

- name: Import Drone CI configuration and run tests
  hosts: drone_hosts
  become: true
  gather_facts: true
  roles:
    - drone
  tasks:
    - name: Import Drone test tasks
      ansible.builtin.import_tasks: "tasks/test.yml"
