---
# Standalone disk monitoring playbook
# Apply disk monitoring role to hosts that have it enabled in their host_roles

- name: Configure disk monitoring
  hosts: all
  become: true
  pre_tasks:
    - name: Set role facts for conditional execution
      ansible.builtin.set_fact:
        _run_disk_monitoring: "{{ 'disk-monitoring' in host_roles | default([]) }}"

    - name: Debug role facts
      ansible.builtin.debug:
        msg:
          - "host_roles: {{ host_roles | default([]) }}"
          - "_run_disk_monitoring: {{ _run_disk_monitoring }}"

  roles:
    - role: disk-monitoring
      when: _run_disk_monitoring | bool
