---
# Main infrastructure playbook
# Applies roles to hosts based on host_roles inventory variable

- name: Configure infrastructure services
  hosts: all
  become: true
  pre_tasks:
    - name: Set role facts for conditional execution
      ansible.builtin.set_fact:
        _run_nut: "{{ 'nut' in host_roles | default([]) }}"
        _run_watchtower: "{{ 'watchtower' in host_roles | default([]) }}"
        _run_nvidia_gpu: "{{ 'nvidia-gpu' in host_roles | default([]) }}"
        _run_drone: "{{ 'drone' in host_roles | default([]) }}"
        _run_drone_runner_exec: "{{ 'drone-runner-exec' in host_roles | default([]) }}"
        _run_disk_monitoring: "{{ 'disk-monitoring' in host_roles | default([]) }}"
        _run_gitea: "{{ 'gitea' in host_roles | default([]) }}"
        _run_gitea_act_runner: "{{ 'gitea-act-runner' in host_roles | default([]) }}"

  roles:
    - role: nut
      when: _run_nut | bool
    - role: watchtower
      when: _run_watchtower | bool and not _run_nvidia_gpu | bool
    - role: nvidia-gpu
      when: _run_nvidia_gpu | bool
    - role: drone
      when: _run_drone | bool
    - role: drone-runner-exec
      when: _run_drone_runner_exec | bool
    - role: disk-monitoring
      when: _run_disk_monitoring | bool
    - role: gitea
      when: _run_gitea | bool
    - role: gitea-act-runner
      when: _run_gitea_act_runner | bool
