---
# NVIDIA GPU-only deployment playbook for testing/development

- name: Deploy NVIDIA GPU configuration
  hosts: all
  become: true
  roles:
    - role: nvidia-gpu
      when: "'nvidia-gpu' in host_roles | default(['nvidia-gpu'])"
