---
# Watchtower-only deployment playbook for testing/development

- name: Deploy Watchtower container updates
  hosts: all
  become: true
  roles:
    - role: watchtower
      when: "'watchtower' in host_roles | default(['watchtower'])"
