---
# Setup Watchtower for automatic container updates

- name: Verify docker-compose is available
  ansible.builtin.command: docker compose version
  register: docker_compose_check
  changed_when: false
  ignore_errors: true
  when: install_watchtower | bool

- name: Fail if docker-compose is not available
  ansible.builtin.fail:
    msg: "Docker compose is not available. Please ensure docker and docker-compose are properly installed."
  when:
    - install_watchtower | bool
    - docker_compose_check.rc != 0

- name: Create watchtower directory
  ansible.builtin.file:
    path: "{{ watchtower_install_dir }}"
    state: directory
    mode: "0755"
  when: install_watchtower | bool

- name: Create watchtower docker-compose.yml file
  ansible.builtin.template:
    src: watchtower-unified.yml.j2
    dest: "{{ watchtower_install_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  register: watchtower_config_updated
  when: install_watchtower | bool

- name: Create watchtower service file
  ansible.builtin.template:
    src: watchtower.service.j2
    dest: /etc/systemd/system/watchtower.service
    owner: root
    group: root
    mode: "0644"
  register: service_file_updated
  when: install_watchtower | bool

- name: Force systemd reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: install_watchtower | bool and service_file_updated is changed

- name: Enable and start watchtower service
  ansible.builtin.systemd:
    name: watchtower
    enabled: true
    state: "{{ 'restarted' if service_file_updated is changed or watchtower_config_updated is changed else 'started' }}"
    daemon_reload: true
  register: watchtower_service
  when: install_watchtower | bool

- name: Wait for watchtower container to start
  ansible.builtin.shell: docker ps | grep watchtower
  register: watchtower_container
  changed_when: false
  ignore_errors: true
  retries: 15
  delay: 4
  until: watchtower_container.rc == 0
  when: install_watchtower | bool

# User-space watchtower setup
- name: Setup user-space watchtower instances
  ansible.builtin.include_tasks: user-watchtower.yml
  loop: "{{ watchtower_user_instances }}"
  when:
    - install_watchtower_user | bool
    - watchtower_user_instances | length > 0
