---
# Tasks for setting up Gitea Act Runner using Docker Compose

- name: Ensure directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ gitea_act_runner_dir }}"
    - "{{ gitea_act_runner_dir }}/data"
    - "{{ gitea_act_runner_dir }}/docker-compose"

- name: Create Docker Compose file for Gitea Act Runner
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gitea_act_runner_dir }}/docker-compose/docker-compose.yml"
    mode: "0644"
  register: compose_template

- name: Start Gitea Act Runner using docker compose
  become: true
  ansible.builtin.command: "sudo docker compose up -d --pull always --force-recreate"
  args:
    chdir: "{{ gitea_act_runner_dir }}/docker-compose"
  register: compose_result
  changed_when: "'Creating' in compose_result.stdout or 'Recreating' in compose_result.stdout or 'Starting' in compose_result.stdout"

- name: Verify container is running
  ansible.builtin.shell: set -o pipefail; sudo docker ps | grep watchtower
  retries: 15
  delay: 4
  until: container_check.rc == 0
  become: true
  register: container_check
  changed_when: false
  failed_when: false

- name: Fail if container is not running
  ansible.builtin.fail:
    msg: "Gitea Act Runner container is not running"
  when: container_check.rc != 0
