---
# Test playbook for Gitea role

- name: Define gitea group dynamically
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host to gitea_hosts group if it has the role
      ansible.builtin.group_by:
        key: "gitea_hosts"
      when: "'gitea' in hostvars[inventory_hostname].get('host_roles', [])"

- name: Import Gitea configuration playbook
  hosts: gitea_hosts
  become: true
  gather_facts: true
  tasks:
    - name: Include gitea default variables
      ansible.builtin.include_vars:
        file: "defaults/main.yml"

    - name: Include host-specific variables
      ansible.builtin.include_vars:
        file: "vars/main.yml"
      failed_when: false

    - name: Include gitea tasks
      ansible.builtin.include_tasks: "tasks/main.yml"

- name: Validate Gitea configuration
  hosts: gitea_hosts
  become: true
  gather_facts: true
  tasks:
    - name: Include gitea default variables for validation
      ansible.builtin.include_vars:
        file: "defaults/main.yml"

    - name: Include host-specific variables for validation
      ansible.builtin.include_vars:
        file: "vars/main.yml"
      failed_when: false

    - name: Import Gitea test tasks
      ansible.builtin.import_tasks: "tasks/test.yml"
