---
# NUT (Network UPS Tools) setup tasks

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install APT packages
  ansible.builtin.apt:
    pkg:
      - nut
      - python3
      - pipx
    state: present
    cache_valid_time: 3600

- name: Make sure destination dir exists
  ansible.builtin.file:
    path: "{{ nut_conf_path | dirname }}"
    state: directory
    mode: "0755"

- name: Create nut.conf
  ansible.builtin.template:
    src: nut.conf.j2
    dest: "{{ nut_conf_path }}"
    owner: root
    group: nut
    mode: "0640"
  register: nut_conf

- name: Create notifycmd
  ansible.builtin.template:
    src: client/notifycmd.j2
    dest: "/etc/nut/notifycmd"
    owner: root
    group: nut
    mode: "0644"
  when: nut_mode == 'netclient'

- name: Create upsmon.conf
  ansible.builtin.template:
    src: client/upsmon.conf.j2
    dest: "{{ upsmon_conf_path }}"
    owner: root
    group: nut
    mode: "0640"
  register: upsmon_conf
  when: nut_mode == 'netclient'

- name: Restart nut
  ansible.builtin.service:
    name: "{{ (ansible_distribution == 'Debian') | ternary('nut.target', 'nut-monitor') }}"
    state: restarted
  when: nut_conf.changed or upsmon_conf.changed
  ignore_errors: "{{ ansible_check_mode }}"
