---
# NVIDIA GPU Configuration Example Variables
# Copy this file to main.yml and customize as needed

# Enable/disable feature flags
nvidia_install_gpu_drivers: true # Whether to install NVIDIA GPU drivers
nvidia_install_cuda_toolkit: true # Whether to install CUDA toolkit
install_btop: true # Whether to install btop
install_ollama: true # Whether to install Ollama
install_uv: true # Whether to install uv Python package manager
install_n8n: true # Whether to install n8n AI workflow platform
install_whisper_asr: true # Whether to install Whisper ASR Webservice
install_open_webui: true # Whether to install Open WebUI
install_comfyui: true # Whether to install ComfyUI for image generation
install_docker_compose: true # Whether to install latest docker-compose
nvidia_configure_egpu: true # Whether to configure thunderbolt eGPU support
install_watchtower: true # Whether to install watchtower for automatic container updates

# Package versions and configuration
nvidia_driver_version: "570" # Used in package name (nvidia-driver-570)
btop_version: "1.4.0" # Version to install from GitHub releases
n8n_version: "main" # Git branch or tag to use for n8n installation

# NVIDIA Container Runtime options
nvidia_container_debug: false # Set to true for debugging
nvidia_runtime_debug: false # Set to true for debugging
nvidia_load_kmods: true # Load kernel modules automatically
nvidia_no_cgroups: false # Set to true to disable cgroups support
nvidia_require_cuda: true # Require CUDA support

# n8n configuration
n8n_install_dir: "/opt/n8n-ai-starter-kit" # Installation directory
n8n_port: "5678" # Port for n8n web interface
n8n_protocol: "http" # Protocol for n8n web interface (http or https)
n8n_host: "localhost" # Host for n8n web interface
n8n_host_public: "localhost" # Public host for n8n web interface
n8n_webhook_url: "https://example.com/"

# n8n database configuration
n8n_postgres_user: "n8n" # PostgreSQL username
n8n_postgres_password: "n8n_password" # PostgreSQL password (change in production)
n8n_postgres_db: "n8n" # PostgreSQL database name
n8n_encryption_key: "12345678901234567890123456789012" # 32-character encryption key (change in production)

# Whisper ASR Webservice configuration
whisper_asr_install_dir: "/opt/whisper-asr" # Installation directory
whisper_asr_port: "9000" # Port for Whisper ASR API
whisper_asr_model: "large-v3" # Model size (tiny, base, small, medium, large, large-v3)
whisper_asr_engine: "faster_whisper" # Engine: faster_whisper or whisper
whisper_asr_compute_type: "{% if nvidia_install_gpu_drivers | bool %}float16{% else %}int8{% endif %}" # Compute type: float16 (GPU), int8 (CPU)

# Open WebUI configuration
open_webui_install_dir: "/opt/open-webui" # Installation directory
open_webui_port: "3000" # Port for Open WebUI
open_webui_enable_rag_web_search: true # Enable RAG web search
open_webui_enable_search_query_generation: true # Enable search query generation
open_webui_rag_web_search_engine: "duckduckgo" # Web search engine to use
open_webui_rag_web_loader_engine: "playwright" # Web loader engine to use
open_webui_enable_image_generation: true # Enable image generation integration

# ComfyUI configuration
comfyui_install_dir: "/opt/comfyui" # Installation directory
comfyui_port: "8188" # Port for ComfyUI
comfyui_user: "comfyui" # User to run ComfyUI
comfyui_group: "comfyui" # Group for ComfyUI user
comfyui_create_user: true # Whether to create a dedicated user for ComfyUI
comfyui_venv_path: "/opt/comfyui/venv" # Path to Python virtual environment
comfyui_git_repo: "https://github.com/comfyanonymous/ComfyUI.git" # Git repository
comfyui_git_branch: "master" # Git branch or tag
comfyui_torch_cuda_url: "https://download.pytorch.org/whl/cu121" # PyTorch CUDA wheels URL
comfyui_low_vram: true # Enable low VRAM mode (8GB VRAM or less)
comfyui_force_reinstall: false # Set to true to force removal and reinstallation

# Watchtower configuration
watchtower_install_dir: "/opt/watchtower" # Installation directory
watchtower_version: "latest" # Version of watchtower to use
watchtower_debug: false # Enable debug logging
watchtower_cleanup: true # Remove old images after updating
watchtower_include_stopped: false # Include stopped containers when checking for updates
watchtower_rolling_restart: true # Restart one container at a time
watchtower_schedule: "0 0 4 * * *" # Update at 4 AM (cron format)
watchtower_poll_interval: "86400" # Check every 24 hours (in seconds, alternative to schedule)
watchtower_monitor_only_enable: [] # Only monitor containers with specific labels
watchtower_notifications_enabled: false # Enable notifications
watchtower_pushover_app_token: "app_token_here" # Pushover application token/key
watchtower_pushover_user_key: "user_key_here" # Pushover user key

# Container update flags (set to true to enable automatic updates for specific containers)
watchtower_update_n8n: true # Update n8n container
watchtower_update_postgres: false # Update PostgreSQL container (generally not recommended)
watchtower_update_qdrant: true # Update Qdrant container
watchtower_update_whisper_asr: true # Update Whisper ASR container
watchtower_update_open_webui: true # Update Open WebUI container

