---
# NVIDIA GPU Configuration Example Variables
# Copy this file to main.yml and customize as needed

# Enable/disable feature flags
nvidia_install_gpu_drivers: true # Whether to install NVIDIA GPU drivers
nvidia_install_cuda_toolkit: true # Whether to install CUDA toolkit
install_btop: true # Whether to install btop
install_ollama: true # Whether to install Ollama
install_uv: true # Whether to install uv Python package manager
nvidia_configure_egpu: true # Whether to configure thunderbolt eGPU support

# Package versions and configuration
nvidia_driver_version: "570" # Used in package name (nvidia-driver-570)
btop_version: "1.4.0" # Version to install from GitHub releases

# NVIDIA Container Runtime options
nvidia_container_debug: false # Set to true for debugging
nvidia_runtime_debug: false # Set to true for debugging
nvidia_load_kmods: true # Load kernel modules automatically
nvidia_no_cgroups: false # Set to true to disable cgroups support
nvidia_require_cuda: true # Require CUDA support

