---
# Test playbook for Disk Monitoring configuration

- name: Define disk-monitoring group dynamically
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host to disk_monitoring group if it has the role
      ansible.builtin.group_by:
        key: "disk_monitoring_hosts"
      when: "'disk-monitoring' in hostvars[inventory_hostname].get('host_roles', [])"
      changed_when: false

- name: Validate Disk Monitoring configuration
  hosts: disk_monitoring_hosts
  become: true
  gather_facts: true
  roles:
    - disk-monitoring
  tasks:
    - name: Import Disk Monitoring test tasks
      ansible.builtin.import_tasks: "tasks/test.yml"
