---
# Gitea role playbook for Synology NAS

- name: Deploy Gitea on Synology NAS
  hosts: "{{ target | default('synology1') }}"
  gather_facts: true
  vars:
    synology_docker_path: "/usr/local/bin/docker"
    docker_cmd: "{{ synology_docker_path }}"

  pre_tasks:
    - name: Check for Synology DSM
      stat:
        path: /etc/synoinfo.conf
      register: synoinfo

    - name: Set fact that this is a Synology device
      set_fact:
        is_synology: "{{ synoinfo.stat.exists | default(false) }}"

    - name: Debug - Is Synology
      debug:
        msg: "Is Synology: {{ is_synology }}"

    - name: Verify Docker is available on Synology
      stat:
        path: "{{ synology_docker_path }}"
      register: synology_docker_binary
      when: is_synology

    - name: Set proper Docker command path
      set_fact:
        docker_cmd: "{{ synology_docker_path }}"
      when: is_synology and synology_docker_binary.stat.exists

    - name: Debug docker command path
      debug:
        msg: "Using Docker command: {{ docker_cmd }}"

    - name: Check Docker version (verify Docker is working)
      command: "{{ docker_cmd }} version"
      register: docker_version
      changed_when: false
      failed_when: false

    - name: Debug Docker version output
      debug:
        msg: "Docker version output: {{ docker_version.stdout | default('Not available') }}"

    - name: Fail if Docker is not available
      fail:
        msg: "Docker is not available on the target host. Output: {{ docker_version.stderr | default('No error message') }}"
      when: docker_version.rc != 0

    - name: Check if Docker Compose v2 is available
      command: "{{ docker_cmd }} compose version"
      register: compose_check
      changed_when: false
      failed_when: false

  tasks:
    - name: Include Gitea tasks
      include_tasks: tasks/main.yml
