---
# NUT (Network UPS Tools) setup playbook
# This playbook maintains compatibility with terraform usage
# while enabling role-based infrastructure composition

- name: Setup nut UPS monitoring  
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
    - group_vars/all.yml
  tasks:
    - name: Import NUT role tasks
      ansible.builtin.import_tasks: tasks/main.yml