---
# Playbook for applying Drone CI and Runner roles to hosts

- name: Import Drone CI configuration playbook
  import_playbook: drone/main.yml
  vars:
    target_hosts: "{{ groups['all'] | select('extract', hostvars, 'host_roles') | selectattr('host_roles', 'contains', 'drone') | list }}"

- name: Import Drone Runner Exec configuration playbook
  import_playbook: drone-runner-exec/main.yml
  vars:
    target_hosts: "{{ groups['all'] | select('extract', hostvars, 'host_roles') | selectattr('host_roles', 'contains', 'drone-runner-exec') | list }}"
