---
# Tasks for managing Gitea on Synology DSM

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ gitea_compose_dir }}"
    - "{{ gitea_data_dir }}"

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: gitea-docker-compose.yml.j2
    dest: "{{ gitea_compose_dir }}/docker-compose.yml"
    mode: "0644"
  register: compose_template

- name: Start Gitea using docker compose
  ansible.builtin.command: "{{ docker_cmd }} compose up -d --pull always"
  args:
    chdir: "{{ gitea_compose_dir }}"
  register: result
  changed_when: "'Creating' in result.stdout or 'Recreating' in result.stdout or 'Starting' in result.stdout"
