---
kind: pipeline
type: docker
name: build-example

steps:
  - name: hello-world
    image: alpine:latest
    commands:
      - echo "Hello from an external pipeline file!"
      - echo "This is a simple example of a pipeline in a separate file"
      - echo "If this runs, your Drone CI supports external pipeline files"
