kind: pipeline
type: docker
name: test-include

steps:
  - name: test-step
    image: alpine:latest
    commands:
      - echo "This is a test pipeline included from .drone/test-include.yml"
      - echo "If you see this in your CI logs, the include feature works!"
