---
# Test playbook for NUT configuration

- name: Define nut group dynamically
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host to nut_hosts group if it has the role
      ansible.builtin.group_by:
        key: "nut_hosts"
      when: "'nut' in hostvars[inventory_hostname].get('host_roles', [])"

- name: Import NUT configuration playbook
  hosts: nut_hosts
  become: true
  gather_facts: true
  roles:
    - nut

- name: Validate NUT configuration
  hosts: nut_hosts
  become: true
  gather_facts: true
  tasks:
    # Using roles instead of manually including vars to maintain proper variable precedence
    - name: Import NUT test tasks
      ansible.builtin.import_tasks: "tasks/test.yml"
