---
# Open WebUI Tasks

- name: Create Open WebUI base directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "{{ open_webui_install_dir }}"
    - "{{ open_webui_install_dir }}/data"

- name: Create systemd service for Open WebUI
  ansible.builtin.template:
    src: open-webui.service.j2
    dest: /etc/systemd/system/open-webui.service
    owner: root
    group: root
    mode: '0644'
  register: open_webui_service_file
  notify: Reload systemd

- name: Enable and start Open WebUI service
  ansible.builtin.systemd:
    name: open-webui
    enabled: yes
    state: started
    daemon_reload: yes
  ignore_errors: "{{ ansible_check_mode }}"
  
- name: Restart Open WebUI service if service file changed
  ansible.builtin.systemd:
    name: open-webui
    state: restarted
  when: open_webui_service_file.changed