---
# Setup Watchtower for automatic container updates

- name: Ensure docker-compose is installed
  ansible.builtin.assert:
    that: install_docker_compose | bool
    fail_msg: "Watchtower requires docker-compose to be installed (set install_docker_compose: true)"
  when: install_watchtower | bool
    
- name: Create watchtower directory
  ansible.builtin.file:
    path: "{{ watchtower_install_dir }}"
    state: directory
    mode: "0755"
  when: install_watchtower | bool

- name: Create watchtower docker-compose.yml file
  ansible.builtin.template:
    src: watchtower-docker-compose.yml.j2
    dest: "{{ watchtower_install_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  register: watchtower_config_updated
  when: install_watchtower | bool

- name: Create watchtower service file
  ansible.builtin.template:
    src: watchtower.service.j2
    dest: /etc/systemd/system/watchtower.service
    owner: root
    group: root
    mode: "0644"
  register: service_file_updated
  when: install_watchtower | bool

- name: Force systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes
  when: install_watchtower | bool and service_file_updated is changed

- name: Enable and start watchtower service
  ansible.builtin.systemd:
    name: watchtower
    enabled: yes
    state: "{{ 'restarted' if service_file_updated is changed or watchtower_config_updated is changed else 'started' }}"
    daemon_reload: yes
  register: watchtower_service
  when: install_watchtower | bool

- name: Check docker-compose command exists
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_binary
  when: install_watchtower | bool

- name: Display docker binary path
  ansible.builtin.debug:
    msg: "Docker binary found at /usr/bin/docker: {{ docker_binary.stat.exists }}"
  when: install_watchtower | bool

- name: Check docker-compose command
  ansible.builtin.command: docker compose version
  register: docker_compose_cmd
  changed_when: false
  ignore_errors: true
  when: install_watchtower | bool

- name: Display docker-compose command result
  ansible.builtin.debug:
    msg: "Docker compose command result: {{ docker_compose_cmd.rc == 0 }}"
  when: install_watchtower | bool and docker_compose_cmd is defined

- name: Wait for watchtower container to start
  ansible.builtin.shell: docker ps | grep watchtower
  register: watchtower_container
  changed_when: false
  ignore_errors: true
  retries: 15
  delay: 4
  until: watchtower_container.rc == 0
  when: install_watchtower | bool