---
# Test playbook for Gitea Act Runner role

- name: Define gitea-act-runner group dynamically
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host to gitea_act_runner_hosts group if it has the role
      ansible.builtin.group_by:
        key: "gitea_act_runner_hosts"
      when: "'gitea-act-runner' in hostvars[inventory_hostname].get('host_roles', [])"

- name: Import Gitea Act Runner configuration playbook
  hosts: gitea_act_runner_hosts
  become: true
  gather_facts: true
  roles:
    - gitea-act-runner

- name: Validate Gitea Act Runner CI configuration
  hosts: gitea_act_runner_hosts
  become: true
  gather_facts: true
  tasks:
    - name: Include gitea-act-runner default variables for validation
      ansible.builtin.include_vars:
        file: "defaults/main.yml"

    - name: Include host-specific variables for validation
      ansible.builtin.include_vars:
        file: "vars/main.yml"

    - name: Import Gitea Act Runner test tasks
      ansible.builtin.import_tasks: "tasks/test.yml"
