---
# Test playbook for Drone CI configuration

- name: Import Drone CI configuration playbook
  hosts: all
  become: true
  tasks:
    - name: Include drone default variables
      ansible.builtin.include_vars:
        file: defaults/main.yml

    - name: Include host-specific variables if they exist
      ansible.builtin.include_vars:
        file: vars/main.yml
      ignore_errors: true

    - name: Include drone tasks
      ansible.builtin.include_tasks: tasks/main.yml

- name: Validate Drone CI configuration
  hosts: all
  become: true
  tasks:
    - name: Include drone default variables for validation
      ansible.builtin.include_vars:
        file: defaults/main.yml

    - name: Include host-specific variables for validation if they exist
      ansible.builtin.include_vars:
        file: vars/main.yml
      ignore_errors: true

    - name: Import Drone test tasks
      ansible.builtin.import_tasks: tasks/test.yml
